name: flask_label
dependencies:
  - python=3.6.5
  - pip
  - pip:
    - autopep8
    - grpcio
    - pylint
    - pytest
    - coverage
    - protobuf-compiler
    - python-dotenv
    - Pillow
    - -e .