FROM ubuntu:16.04

RUN apt-get update && apt-get install -y \
        curl \
        gnupg \
        tar

ARG TF_SERVING_VERSION=1.8.0
ARG TF_SERVING_PKGNAME=tensorflow-model-server
RUN curl -LO https://storage.googleapis.com/tensorflow-serving-apt/pool/${TF_SERVING_PKGNAME}-${TF_SERVING_VERSION}/t/${TF_SERVING_PKGNAME}/${TF_SERVING_PKGNAME}_${TF_SERVING_VERSION}_all.deb ; \
        dpkg -i ${TF_SERVING_PKGNAME}_${TF_SERVING_VERSION}_all.deb ; \
        rm ${TF_SERVING_PKGNAME}_${TF_SERVING_VERSION}_all.deb

RUN  apt-get clean && rm -rf /var/lib/apt/lists/*

# gRPC
EXPOSE 9000

# REST
EXPOSE 9001

COPY docker/model.conf .

ENTRYPOINT tensorflow_model_server --model_config_file=model.conf --port=9000 --rest_api_port=9001 --enable_batching